### ISSUE TITLE
pre-genesis related questions

### ISSUE THREAD

**Issue by vchong** [anoma/namada-mainnet-genesis#145]
Hi, wrt https://hackmd.io/CNzB-rsNQ1ykRHkj8EDbTA,

1. In cometbft, there's usually a separation between the operator (i.e. validator's owner or validator account) key (usually of secp256k1 scheme) and the consensus (i.e. signing) key (usually of ed25519 scheme), but `namadac utils init-genesis-validator` seems to be deriving the consensus key directly from the validator account key, and both of them default to the ed25519 scheme, so both keys are "tied" together. Is that right?

2. If we elect Scenario 4, that means the bond for the validator comes from the address in `balances.toml`, not from the validator account address, so there's no self-bond. Is that ok? If ok, should we still transfer some tokens from the address in `balances.toml` to the validator account address? In some chains, accounts with 0 balances aren't initialized/activated/enabled and can't really be used.

3. Are the tokens in the address in `balances.toml` liquid?

4. What is the number of validators in the active set at genesis?

5. "the github username in the filenames must match exactly the github account you submit the PR from"
How does this make sense? If I'm github user `johndoe` working for `acme`, I'd want to submit a PR to `Add ACME pre-genesis transaction`, not `Add johndoe pre-genesis transaction`. Also, gh user `johndoe` as an employee of `acme` doesn't necessarily have access to submit from the `https://github.com/acme` organizational account. So is it ok that the company/moniker name in the filenames not match the gh account that submits the PR? PR# 109 is an example of this case, and it seems to be ok.

**Comment by Fraccaman** [comment]
2. transfers are not allowed pre-genesis, only bonding. No worries about addresses not being initialized.
3. liquid, what do you mean? you can read more here https://namada.net/mainnet-launch
4. 255
5. this is only needed for internal accounting, its not gonna be reflected on-chain. PR #109 is not valid and will not be merged.

**Comment by Fraccaman** [comment]
1. no we dont have, but you can change it later
2. yes, but will not be part of consensus set
6. no recommendations

**Comment by Fraccaman** [comment]
1. If you want to use ur own consensus-key i think you can, but we dont have docs about it
2. no vesting period, but tokens are not transferable till phase 5. Consensus set if the set of 255 validators who are validators who are going to validate the chain. You can bond/self-bond to ur validator in phase 2. The 255 validators with the highest voting power will be selected by the protocol to be part of consensus set.

**Comment by Fraccaman** [comment]
2. if the total amount of voting power of your validator is greater than the 255th validator, yes
