### ISSUE TITLE
Validator key 

### ISSUE THREAD

**Issue by AlexITProf** [anoma/namada-mainnet-genesis#769]
Hello, pls help. 
I can't do anything using the validator key: 

REQUEST1:
alex@MAIN-1:~$  namadac rewards --validator alexit-validator
ANSWER1:
Current rewards available for claim: 0.542193 NAM

REQUEST2:
alex@MAIN-1:~$ namadac claim-rewards --validator alexit-validator
ANSWER2:
Looking-up public key of tnam1q83z54q574kvzfujk5dt9kpy42a4zpassueswgyq from the ledger...
Error:
   0: unable to sign transaction with tpknam1qzsmt8lksjezlepf2zcj58uw0s8m43ur8x8j8u6fspzm73xlcysxxa56685

Location:
   /home/runner/work/namada/namada/crates/apps_lib/src/cli/client.rs:285

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

REQUEST3:
alex@MAIN-1:~$ namada client query-account --owner alexit-validator
ANSWER3:
Address: tnam1q83z54q574kvzfujk5dt9kpy42a4zpassueswgyq
Threshold: 1
Public keys:
- tpknam1qzsmt8lksjezlepf2zcj58uw0s8m43ur8x8j8u6fspzm73xlcysxxa56685

**Comment by brentstone** [comment]
Please reach out on the namada discord to the `mainnet-coordination` channel or me, @Brent. Do not use the github repos for such support pls.
